from pathlib import Path

SCRIPT = Path('kspjewelrycrafter/KspJewelryCrafterScript.java')
PLUGIN = Path('kspjewelrycrafter/KspJewelryCrafterPlugin.java')

text = SCRIPT.read_text(encoding='utf-8')

text = text.replace(
    'import net.runelite.api.GrandExchangeOffer;\n',
    'import net.runelite.api.GameObject;\nimport net.runelite.api.GrandExchangeOffer;\nimport net.runelite.api.MenuAction;\nimport net.runelite.api.ObjectComposition;\nimport net.runelite.api.TileObject;\n'
)
# TileObject already existed in the source; collapse any duplicate generated by the insertion.
text = text.replace('import net.runelite.api.TileObject;\nimport net.runelite.api.TileObject;\n', 'import net.runelite.api.TileObject;\n')
text = text.replace(
    'import net.runelite.client.plugins.microbot.kspmule.KspMuleWorkerService;\n',
    'import net.runelite.client.plugins.microbot.kspmule.KspMuleWorkerService;\nimport net.runelite.client.plugins.microbot.util.menu.NewMenuEntry;\nimport net.runelite.client.plugins.microbot.util.misc.Rs2UiHelper;\n'
)

old_bank = '''        if (!Rs2Bank.openBank())\n        {\n            if (System.currentTimeMillis() - attemptStartedAt < 750L) bankInteractionSentAt = 0L;\n            else bankInteractionSentAt = System.currentTimeMillis();\n            status = bankInteractionSentAt > 0L\n                ? (Rs2Player.isMoving() ? "Approaching bank" : "Waiting for bank widget")\n                : "Bank target not ready";\n            return false;\n        }\n'''
new_bank = '''        if (!openBankWithoutCamera(edgeville))\n        {\n            if (System.currentTimeMillis() - attemptStartedAt < 750L) bankInteractionSentAt = 0L;\n            else bankInteractionSentAt = System.currentTimeMillis();\n            status = bankInteractionSentAt > 0L\n                ? (Rs2Player.isMoving() ? "Approaching bank" : "Waiting for bank widget")\n                : "Bank target not ready";\n            return false;\n        }\n'''
if old_bank not in text:
    raise RuntimeError('Bank interaction block not found')
text = text.replace(old_bank, new_bank, 1)

old_furnace = '''            if (!Rs2GameObject.interact(furnace, "Smelt"))\n            {\n                status = "Unable to use Edgeville furnace";\n                return;\n            }\n'''
new_furnace = '''            if (!interactGameObjectWithoutCamera(furnace, "Smelt"))\n            {\n                status = "Unable to use Edgeville furnace";\n                return;\n            }\n'''
if old_furnace not in text:
    raise RuntimeError('Furnace interaction block not found')
text = text.replace(old_furnace, new_furnace, 1)

anchor = '''    private boolean closeBankIfDone(String closingStatus)\n'''
if anchor not in text:
    raise RuntimeError('Helper insertion anchor not found')

helpers = '''    /**\n     * Opens a bank without invoking Microbot's normal object interaction helper.\n     * That helper rotates the camera when the target is off-screen; Jewellery\n     * Crafter deliberately leaves the camera untouched and dispatches the Bank\n     * menu action directly instead.\n     */\n    private boolean openBankWithoutCamera(boolean edgeville)\n    {\n        GameObject bank = Rs2GameObject.findBank();\n        if (bank != null)\n        {\n            return interactGameObjectWithoutCamera(bank, "Bank");\n        }\n\n        // Do not fall back to Rs2Bank.openBank(), because its banker/object path\n        // can rotate the camera as well. Move close enough for a bank object to\n        // enter the scene and retry on the next script tick.\n        WorldPoint destination = edgeville ? EDGEVILLE_BANK : EDGEVILLE_BANK;\n        status = edgeville ? "Approaching Edgeville bank" : "Walking to bank without camera movement";\n        if (!Rs2Player.isMoving()) Rs2Walker.walkTo(destination, 10);\n        return false;\n    }\n\n    /**\n     * Dispatches a game-object action without Rs2Camera.turnTo(...). This is a\n     * local equivalent of the normal object click path minus camera movement.\n     */\n    private boolean interactGameObjectWithoutCamera(TileObject tileObject, String action)\n    {\n        if (!(tileObject instanceof GameObject) || action == null || action.isBlank()) return false;\n        GameObject object = (GameObject) tileObject;\n\n        ObjectComposition composition = Microbot.getClientThread().runOnClientThreadOptional(() ->\n        {\n            ObjectComposition resolved = Microbot.getClient().getObjectDefinition(object.getId());\n            if (resolved != null && resolved.getImpostorIds() != null && resolved.getImpostor() != null)\n                resolved = resolved.getImpostor();\n            return resolved;\n        }).orElse(null);\n        if (composition == null) return false;\n\n        String[] actions = composition.getActions();\n        if (actions == null) return false;\n        int actionIndex = -1;\n        for (int i = 0; i < actions.length; i++)\n        {\n            if (actions[i] != null && action.equalsIgnoreCase(actions[i]))\n            {\n                actionIndex = i;\n                break;\n            }\n        }\n        if (actionIndex < 0) return false;\n\n        MenuAction menuAction = gameObjectMenuAction(actionIndex);\n        if (menuAction == null) return false;\n\n        int sceneX = object.getLocalLocation().getSceneX();\n        int sceneY = object.getLocalLocation().getSceneY();\n        if (object.sizeX() > 1) sceneX -= object.sizeX() / 2;\n        if (object.sizeY() > 1) sceneY -= object.sizeY() / 2;\n\n        NewMenuEntry entry = new NewMenuEntry()\n            .param0(sceneX)\n            .param1(sceneY)\n            .opcode(menuAction.getId())\n            .identifier(object.getId())\n            .itemId(-1)\n            .option(actions[actionIndex])\n            .target(composition.getName())\n            .gameObject(object);\n\n        Microbot.doInvoke(entry, Rs2UiHelper.getObjectClickbox(object));\n        return true;\n    }\n\n    private MenuAction gameObjectMenuAction(int actionIndex)\n    {\n        switch (actionIndex)\n        {\n            case 0: return MenuAction.GAME_OBJECT_FIRST_OPTION;\n            case 1: return MenuAction.GAME_OBJECT_SECOND_OPTION;\n            case 2: return MenuAction.GAME_OBJECT_THIRD_OPTION;\n            case 3: return MenuAction.GAME_OBJECT_FOURTH_OPTION;\n            case 4: return MenuAction.GAME_OBJECT_FIFTH_OPTION;\n            default: return null;\n        }\n    }\n\n'''
text = text.replace(anchor, helpers + anchor, 1)

SCRIPT.write_text(text, encoding='utf-8')

plugin = PLUGIN.read_text(encoding='utf-8')
if 'public static final String VERSION = "0.1.26";' not in plugin:
    raise RuntimeError('Expected Jewellery Crafter version not found')
plugin = plugin.replace('public static final String VERSION = "0.1.26";', 'public static final String VERSION = "0.1.27";', 1)
PLUGIN.write_text(plugin, encoding='utf-8')

Path('.github/workflows/patch-jewelry-no-camera.yml').unlink(missing_ok=True)
Path('.github/scripts/patch_jewelry_no_camera.py').unlink(missing_ok=True)
